### ISSUE TITLE
Q&A

### ISSUE THREAD

**Issue by LuongXuanNhat** [LuongXuanNhat/MULTIPLE-CHOICE-EXAM-APP#1]
Nếu có trục trặc và vấn đề gì về code: Hãy đặt câu hỏi cho mình và mình sẽ phản hồi cũng như hỗ trợ (nếu có thể). Cảm ơn

**Comment by inuwakii** [comment]
ad ơi làm sao để tải về và chạy được trên máy vậy ạ

**Comment by LuongXuanNhat** [comment]
> ad ơi làm sao để tải về và chạy được trên máy vậy ạ

Mình vừa cập nhập lại code | Bạn chỉ cần pull về và chạy lệnh Update-Migration là được nhé! Nếu có vấn đề khác hãy hỏi nhé
